services:
  promanage-backend:
    container_name: promanage-backend
    build: 
      context: ./promanage-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=promanage-db
      - DB_PORT=5432
      - PYTHONPATH="/app"
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@promanage-db:5432/${DB_NAME}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      
    env_file:
      - .env
      
    depends_on:
      promanage-db:
        condition: service_healthy
    command: /app/entrypoint.sh
      
  promanage-db:
    container_name: promanage-db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
