services:
  backend:
    build:
      #context: .
      context: ./promanage-backend
      #dockerfile: ./promanage-backend/Dockerfile
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./promanage-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - promanage-db
  
  frontend:
    build:
      context: ./promanage-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./promanage-frontend:/app
    command: npm start

  promanage-db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: