services:
  backend:
    build:
      context: ./promanage-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./promanage-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  frontend:
    build:
      context: ./promanage-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./promanage-frontend:/app
    command: npm start
