# Generated by Django 5.1.6 on 2025-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('EXPERIENCE', 'Expérience professionnelle'), ('EDUCATION', 'Formation'), ('SKILL', 'Compétence'), ('CERTIFICATE', 'Certificat')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
