# Generated by Django 5.1.6 on 2025-03-21 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cventry',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'Entrée de CV', 'verbose_name_plural': 'Entrées de CV'},
        ),
        migrations.RemoveField(
            model_name='cventry',
            name='is_public',
        ),
        migrations.AddField(
            model_name='cventry',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='entry_type',
            field=models.CharField(choices=[('EXPERIENCE', 'Expérience'), ('FORMATION', 'Formation'), ('COMPETENCE', 'Compétence'), ('LANGUE', 'Langue'), ('PROJET', 'Projet')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='cventry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du CV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cventry',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cv.curriculumvitae'),
        ),
    ]
